### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/DiscoverMeteor_bg#2]
@SachaG  @VessoVit 

Hello, whats the status of this translation? Would it happen ? I see Vesso haven't been active for at least a year now. Even if I want to contribute who is the repo maintainer ?  Also as Discover Meteor has changed for the past year is it possible to start fresh with this task ? I can dedicate around 10-15 hours/week to that initiative.

Best regards,
L

**Comment by VessoVit** [comment]
Hey, 

If you are in I can be active again. I've some uncommitted contributes, but not much. From March on, I can do 15h, no problem. We can get it done. 

Поздрави!

**Comment by VessoVit** [comment]
@Findegil 

Shall we start with it ?

**Comment by ghost** [comment]
Please provide any assets that I need to get started and let's separate the work somehow
